name: Autotag

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Auto tag
        uses: Klemensas/action-autotag@stable
        with:
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
